### PR TITLE
refactor: attempt to fix GA issue

### LINKED ISSUE #28: Add Google Analytics Tracking Info
Add gtag.js tracking info to the website

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-77563678-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-77563678-4');
</script>
```

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
#### What does this PR do

This PR attempts to make GA start tracking successfully and updates some minor SEO configs.

#### What are the relevant issues this PR belongs to

Fixes #28

### CODE REVIEW

File: src/utils/analytics.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import ReactGA from "react-ga";
 
 export const initGA = () => {
-  ReactGA.initialize(`${process.env.GOOGLE_ANALYTICS}`);
+  ReactGA.initialize(`${process.env.NEXT_PUBLIC_ANALYTICS_ID}`);
```
Comment (alabobriggs) [inline src/utils/analytics.ts:4]: 🎉

**Review by alabobriggs — APPROVED** [review]
looks good

**Comment by alabobriggs** [comment]
Free to merge
